import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-br' className='max-h-screen'>
      <body className='bg-main text-white font-main'>
        <header className='bg-linear-to-b from-gradientHeaderStart/40 from-30% to-gradientHeaderEnd/100 to-100% w-screen flex flex-row justify-center py-5 rounded-b-xl fixed'>
          <h1 className='basis-1 text-center text-base/9'>THE BIBLE</h1>
        </header>
        <main className='grid grid-cols-5 h-screen'>
          {children}
        </main>
      </body>
    </html>
  );
}
